# Generated by Django 5.1.2 on 2025-01-01 14:43
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_tags'),
    ]

    operations = [
        TrigramExtension(),
        # This operation executes the SQL statement
        #  CREATE EXTENSION pg_trgm to create the extension in PostgreSQL.
    ]
